sudo: false

dist: trusty

language: node_js

cache:
  directories:
    - node_modules
    - ~/.npm

before_install:
  - npm i -g npm@5

node_js: 8

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: test
      addons:
        chrome: stable
        firefox: latest
      before_script:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3 # give xvfb some time to start
      script: npm run test:browser
      env:
        - QUICKLY_TEST_BROWSERS_AVAILABLE_IN_CI=1 # kept here for easier reading of build log
    - stage: test
      addons:
        sauce_connect: true
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ -z "$SAUCE_USERNAME" ]; then echo "Cannot run tests without SAUCE_USERNAME"; exit 1; fi'
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then echo "SauceLabs tests do not run in builds of pull requests. This build will now exit"; exit 0; fi'
        - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ -n "$SAUCE_USERNAME" ]; then npm run test:browser; fi'
      env:
        - TEST_BROWSERS_IN_SAUCELABS=1 # kept here for easier reading of build log
        - secure: AgiUWRCNP2z0oHCjdm3lk4YawBOQz8Q4DOrzOR3tDt2fSWo2t40cynfGJlQwpFmTvec5G04lO9bEC9/yoW7xAS0ysu5p7utngXaKtKDoq3Zr0aYLLLsCv/0PAv1YstMyo/mRbRetxob76wUFcrbB3r5alIF5YW1JCmj/O9bvdUQ=
        - secure: TepAZmznoPWUX12snu2eb7Sni+31tiOO6ZeU3wovrhCpGzykBNr6xAvUklr88L+uKtvfsTq8sipX0jtZvL7lcIEzujirTpjaj4QV5mUFiV2N40o+C3LdNmfmU9dhUcXRu9vMSs9uc7YfPers4We8X99UxTHxljK7VyJe39ULpRk=
        - SAUCE_CONNECT_READY_FILE=/tmp/sauce-connect-ready
    - stage: test
      node_js: 8 # to be removed 2019-12-01
      script: npm run test:node
    - stage: test
      node_js: 7 # to be removed 2017-06-30
      script: npm run test:node
    - stage: test
      node_js: 6 # to be removed 2019-04-01
      script: npm run test:node
    - stage: test
      node_js: 4 # to be removed 2018-04-01
      script: npm run test:node
    - stage: test
      node_js: lts/* # safety net; don't remove
      script: npm run test:node
    - stage: test
      node_js: node # safety net; don't remove
      script: npm run test:node
    - stage: semantic-release
      script:
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ] || [ "$TRAVIS_BRANCH" != "master" ]; then echo "the deploy job only runs for the master branch. This build will now exit"; exit 0; fi
        - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then npm run semantic-release; fi
      env:
      - secure: fakflt6DaPW9NYFdUpTfQGoKFt5F1EZeSiGqWeTCZ3+VDiEC/d9rPf7JfHkDklpr4swEW7ovbfV4PHp+MeT+jje8eQAezbhdT8hAmChykeTKKfgvifMwQp6TD3DQVrf6cJqqZfkJkkzuYJjGivZ8FA4KXTglyBrjozM8KH675UU=
      - secure: bE+qM+B4dA+oQSfHo4BM9NVU5LCdgkEmfThfmIp3kmX19RO/1R1dlu18M1rVyDUNaqFUwCsq/W/9a+Dv1r+7knmfmJoUKuXCcIjn6WBs4Pd2kPwjCjvQ+5RWTw67v44de78AFb3IH7dT2H+fhgeHrfaI3NIV27BlKx6OqTnqDRY=

env:
  global:
    - LOGS_DIR=/tmp/chai-build/logs
